# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Wzjk < Formula
  desc "CLI tool for wzjk"
  homepage "https://gitee.com/sandaka/wzjk-cli"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sandakacn/wzjk-cli/releases/download/v1.0.0/wzjk-cli-Darwin-x86_64.tar.gz"
      sha256 "b8686b528287e565c24de5e1cf8f43d2a458765cfccd49db06332312ba3ef9dd"

      define_method(:install) do
        bin.install "wzjk"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sandakacn/wzjk-cli/releases/download/v1.0.0/wzjk-cli-Darwin-aarch64.tar.gz"
      sha256 "49cbba302d43e2cffb6d70f33172d0addeae616164e061ecf6d0691b518ec4e0"

      define_method(:install) do
        bin.install "wzjk"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sandakacn/wzjk-cli/releases/download/v1.0.0/wzjk-cli-Linux-x86_64.tar.gz"
      sha256 "3241529416229f4d6db3d11f3dd8f9c9d54d0c1c5bee40e5fec09d4daa258e18"
      define_method(:install) do
        bin.install "wzjk"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sandakacn/wzjk-cli/releases/download/v1.0.0/wzjk-cli-Linux-aarch64.tar.gz"
      sha256 "61e980ed60528d8023f98b065cc1ed9f21e21d81fbf24ff177fa9cd711ae4a46"
      define_method(:install) do
        bin.install "wzjk"
      end
    end
  end

  test do
    system "#{bin}/wzjk", "--version"
  end
end
